[project]
name = "imagec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nuitka>=2.8.9",
    "ordered-set>=4.1.0",
    "pyinstaller>=6.17.0",
    "zstandard>=0.25.0",
]
